CREATE TABLE IF NOT EXISTS Recipes (
    id INTEGER (18) AUTO_INCREMENT NOT NULL UNIQUE ,
    Recipe VARCHAR_IGNORECASE (250) NOT NULL,
    Description VARCHAR (400));
CREATE TABLE IF NOT EXISTS Ingredients (
    id INTEGER (18) AUTO_INCREMENT NOT NULL UNIQUE,
    Ingredient VARCHAR (250) NOT NULL);
CREATE TABLE IF NOT EXISTS Cookbook (
    id INTEGER (18) AUTO_INCREMENT NOT NULL UNIQUE,
    idRecipe INTEGER (18) NOT NULL,
    idIngredient INTEGER (18) NOT NULL,
    Count VARCHAR (50) NOT NULL,
    Unit VARCHAR (50) NOT NULL,
    FOREIGN KEY (idRecipe) REFERENCES Recipes(id),
    FOREIGN KEY (idIngredient) REFERENCES Ingredients(id));
